#!/usr/bin/env python3
"""
Generate the Coeleo OS site from a single source of truth.

Input
-----
content.json — site facts, shared (non-translatable) structure, and the copy for
every locale.

Output (all committed; the Pages workflow uploads site/ as-is, so there is no
build step in CI):
  site/index.html
  site/pt/index.html
  site/sitemap.xml
  site/llms.txt
  site/llms-full.txt

site/robots.txt and site/404.html stay hand-written: they change rarely and
generating them would add churn for no gain.

Copy that lives in `i18n` is emitted as trusted HTML, so it may contain <code>,
<kbd>, <strong> and entities. Values used in attributes (title, alt, meta
content) and the FAQ answers are escaped instead, which is why they must stay
plain text. Every generated file carries a "do not edit" header.

Run: python3 tools/site-gen/gen.py
"""

import html
import json
import os
import re
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(os.path.dirname(SCRIPT_DIR))
SITE_DIR = os.path.join(REPO_ROOT, "site")
CONTENT = os.path.join(SCRIPT_DIR, "content.json")

GENERATED_BY = "tools/site-gen/gen.py"
HEADER = "Generated by %s from tools/site-gen/content.json. Do not edit by hand." % GENERATED_BY

DOMAIN_COL_WIDTH = 34
DIAGRAM_BOX_LEFT = 16
DIAGRAM_BOX_INNER = 21


def esc(value):
    """Escape a plain-text value for an HTML text node or attribute."""
    return html.escape(str(value), quote=True)


def load_content():
    with open(CONTENT, encoding="utf-8") as handle:
        return json.load(handle)


# --------------------------------------------------------------------------
# Validation: fail loudly instead of shipping a page with a missing string.
# --------------------------------------------------------------------------

_bilingual_cache = {}


def _bilingual_keys(value, path, out):
    """Collect the keys of a {locale: text} shaped subtree."""
    if isinstance(value, dict):
        for key, child in value.items():
            _bilingual_keys(child, "%s.%s" % (path, key), out)
    else:
        out[path] = value


def translated(i18n, locale, path):
    """Fetch `path` for `locale`, caching the flattened locale tree."""
    cache_key = locale
    if cache_key not in _bilingual_cache:
        flat = {}
        _bilingual_keys(i18n[locale], locale, flat)
        _bilingual_cache[cache_key] = flat
    full = "%s.%s" % (locale, path)
    if full not in _bilingual_cache[cache_key]:
        raise SystemExit("content.json: missing translation %r" % full)
    return _bilingual_cache[cache_key][full]


def require(condition, message):
    if not condition:
        raise SystemExit("content.json: %s" % message)


def validate(content, shared):
    locales = [loc["code"] for loc in content["site"]["locales"]]
    i18n = content["i18n"]
    require(sorted(i18n) == sorted(locales), "i18n locales must match site.locales")

    for locale in locales:
        for key in ("meta", "nav", "lightbox", "hero", "reuse", "features", "screenshots",
                    "architecture", "apps", "build", "roadmap", "docs", "faq", "footer"):
            require(key in i18n[locale], "i18n.%s is missing %r" % (locale, key))

        for group in shared["features"]:
            translated(i18n, locale, "features.groups.%s.title" % group["id"])
            for card in group["cards"]:
                translated(i18n, locale, "features.groups.%s.cards.%s.title" % (group["id"], card))
                translated(i18n, locale, "features.groups.%s.cards.%s.body" % (group["id"], card))

        for item in shared["reuse"]:
            translated(i18n, locale, "reuse.items.%s" % item["id"])
        for domain in shared["domains"]:
            translated(i18n, locale, "architecture.domains.%s.name" % domain["id"])
            translated(i18n, locale, "architecture.domains.%s.role" % domain["id"])
        for app in shared["apps"]:
            translated(i18n, locale, "apps.roles.%s" % app["id"])
        for lib in shared["libs"]:
            translated(i18n, locale, "apps.libRoles.%s" % lib["id"])
        for shot in shared["shots"]:
            translated(i18n, locale, "screenshots.shots.%s" % shot["id"])
        for band in shared["roadmap"]:
            translated(i18n, locale, "roadmap.bands.%s.title" % band["id"])
            translated(i18n, locale, "roadmap.bands.%s.desc" % band["id"])
            for phase in band["phases"]:
                translated(i18n, locale, "roadmap.bands.%s.phases.%s.title" % (band["id"], phase))
                translated(i18n, locale, "roadmap.bands.%s.phases.%s.body" % (band["id"], phase))
        for doc in shared["docs"]:
            translated(i18n, locale, "docs.items.%s.label" % doc["id"])
            translated(i18n, locale, "docs.items.%s.note" % doc["id"])

        faq = i18n[locale]["faq"]["items"]
        require(len(faq) >= 1, "i18n.%s.faq.items must not be empty" % locale)
        for entry in faq:
            for field in ("id", "q", "a"):
                require(field in entry, "i18n.%s.faq item missing %r" % (locale, field))
            require("<" not in entry["a"], "faq answers must be plain text (no markup): %s/%s" % (locale, entry["id"]))

    english_ids = [entry["id"] for entry in i18n["en"]["faq"]["items"]]
    for locale in locales:
        other = [entry["id"] for entry in i18n[locale]["faq"]["items"]]
        require(other == english_ids, "faq item ids must match across locales (en vs %s)" % locale)


# --------------------------------------------------------------------------
# Small renderers
# --------------------------------------------------------------------------

def page_url(site, locale):
    return site["baseUrl"] + locale["dir"]


def asset_prefix(locale):
    return "" if not locale["dir"] else "../"


def render_diagram(diagram):
    lines = [
        "  " + diagram["ringLeft"].ljust(DOMAIN_COL_WIDTH) + diagram["ringRight"],
        "  " + ("-" * 32).ljust(DOMAIN_COL_WIDTH) + ("-" * 32),
    ]
    for left, right in zip(diagram["leftLines"], diagram["rightLines"]):
        lines.append("  " + left.ljust(DOMAIN_COL_WIDTH) + right)
    lines.append("")
    lines.append(" " * DIAGRAM_BOX_LEFT + "|" + " " * DIAGRAM_BOX_INNER + "|")
    lines.append(" " * DIAGRAM_BOX_LEFT + "|" + diagram["middle"].center(DIAGRAM_BOX_INNER) + "|")
    lines.append(" " * DIAGRAM_BOX_LEFT + "+" + "-" * DIAGRAM_BOX_INNER + "+")
    for line in diagram["bottomLines"]:
        lines.append(" " * (DIAGRAM_BOX_LEFT + 2) + line)
    return esc("\n".join(lines))


def render_jsonld(content, shared, locale):
    site = content["site"]
    t = content["i18n"][locale["code"]]
    url = page_url(site, locale)
    root = site["baseUrl"]
    repo = site["repoUrl"]
    og_image = root + site["ogImage"]
    license_url = "%s/blob/main/LICENSE-MIT" % repo

    faq_entries = [
        {
            "@type": "Question",
            "name": entry["q"],
            "acceptedAnswer": {"@type": "Answer", "text": entry["a"]},
        }
        for entry in t["faq"]["items"]
    ]

    graph = [
        {
            "@type": "WebSite",
            "@id": "%s#website" % root,
            "url": url,
            "name": site["brand"],
            "description": t["meta"]["description"],
            "inLanguage": locale["hreflang"],
            "publisher": {"@id": "%s#organization" % root},
        },
        {
            "@type": "Organization",
            "@id": "%s#organization" % root,
            "name": site["brand"],
            "url": root,
            "description": t["meta"]["ogDescription"],
            "logo": og_image,
            "sameAs": [repo, "%s/issues" % repo],
        },
        {
            "@type": "SoftwareApplication",
            "@id": "%s#software" % root,
            "name": site["brand"],
            "alternateName": ["CoeleoOS", "coeleo-os"],
            "applicationCategory": "OperatingSystem",
            "applicationSubCategory": "x86_64 operating system",
            "operatingSystem": "x86_64 (UEFI and legacy BIOS)",
            "programmingLanguage": "Rust",
            "runtimePlatform": "x86_64",
            "url": url,
            "inLanguage": locale["hreflang"],
            "description": t["meta"]["description"],
            "license": license_url,
            "isAccessibleForFree": True,
            "offers": {"@type": "Offer", "price": "0", "priceCurrency": "USD"},
            "codeRepository": repo,
            "softwareHelp": "%s/blob/main/docs/contrib/README.md" % repo,
            "author": {"@id": "%s#organization" % root},
            "publisher": {"@id": "%s#organization" % root},
            "sameAs": [repo],
        },
        {
            "@type": "SoftwareSourceCode",
            "@id": "%s#source" % root,
            "name": site["brand"],
            "url": repo,
            "codeRepository": repo,
            "programmingLanguage": {"@type": "ComputerLanguage", "name": "Rust"},
            "runtimePlatform": "x86_64",
            "license": license_url,
            "targetProduct": {"@id": "%s#software" % root},
        },
        {
            "@type": "FAQPage",
            "@id": "%s#faq" % url,
            "inLanguage": locale["hreflang"],
            "isPartOf": {"@id": "%s#website" % root},
            "mainEntity": faq_entries,
        },
    ]

    payload = {"@context": "https://schema.org", "@graph": graph}
    return json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=False)


def render_head(content, shared, locale, other_locales):
    site = content["site"]
    t = content["i18n"][locale["code"]]
    meta = t["meta"]
    prefix = asset_prefix(locale)
    url = page_url(site, locale)
    root = site["baseUrl"]
    og_image = root + site["ogImage"]
    hero_shot = shared["shots"][0]["file"]

    alternate_lines = []
    for candidate in site["locales"]:
        alternate_lines.append(
            '<link rel="alternate" hreflang="%s" href="%s">'
            % (candidate["hreflang"], page_url(site, candidate))
        )
    alternate_lines.append(
        '<link rel="alternate" hreflang="x-default" href="%s">' % page_url(site, site["locales"][0])
    )

    alternate_og = [
        '<meta property="og:locale:alternate" content="%s">' % other["ogLocale"]
        for other in other_locales
    ]

    jsonld = render_jsonld(content, shared, locale)

    return "\n".join([
        "<!DOCTYPE html>",
        "<!-- %s -->" % HEADER,
        '<html lang="%s">' % locale["hreflang"],
        "<head>",
        '<meta charset="utf-8">',
        '<meta name="viewport" content="width=device-width, initial-scale=1">',
        "<title>%s</title>" % esc(meta["title"]),
        '<meta name="description" content="%s">' % esc(meta["description"]),
        '<meta name="author" content="%s">' % esc(site["author"]),
        '<meta name="theme-color" content="#0F1218">',
        '<meta name="color-scheme" content="dark">',
        '<meta name="robots" content="index, follow, max-image-preview:large, max-snippet:-1">',
        "",
        '<link rel="canonical" href="%s">' % url,
        "\n".join(alternate_lines),
        "",
        '<link rel="icon" href="%s%s" type="image/svg+xml">' % (prefix, site["logo"]),
        '<link rel="apple-touch-icon" href="%s%s">' % (prefix, site["iconPng"]),
        '<link rel="preload" as="image" href="%sassets/img/shots/%s" fetchpriority="high">' % (prefix, hero_shot),
        '<link rel="stylesheet" href="%sassets/css/style.css">' % prefix,
        "",
        '<meta property="og:type" content="website">',
        '<meta property="og:site_name" content="%s">' % esc(site["brand"]),
        '<meta property="og:title" content="%s">' % esc(meta["title"]),
        '<meta property="og:description" content="%s">' % esc(meta["ogDescription"]),
        '<meta property="og:url" content="%s">' % url,
        '<meta property="og:locale" content="%s">' % locale["ogLocale"],
        "\n".join(alternate_og),
        '<meta property="og:image" content="%s">' % og_image,
        '<meta property="og:image:width" content="1200">',
        '<meta property="og:image:height" content="630">',
        '<meta property="og:image:type" content="image/jpeg">',
        '<meta property="og:image:alt" content="%s">' % esc(meta["ogImageAlt"]),
        '<meta name="twitter:card" content="summary_large_image">',
        '<meta name="twitter:title" content="%s">' % esc(meta["title"]),
        '<meta name="twitter:description" content="%s">' % esc(meta["ogDescription"]),
        '<meta name="twitter:image" content="%s">' % og_image,
        '<meta name="twitter:image:alt" content="%s">' % esc(meta["ogImageAlt"]),
        "",
        '<script type="application/ld+json">',
        jsonld,
        "</script>",
        "</head>",
    ])


def render_nav(content, locale, other_locales):
    site = content["site"]
    t = content["i18n"][locale["code"]]
    suffix = asset_prefix(locale)
    menu = [
        '      <a href="#%s">%s</a>' % (nid, t["nav"]["labels"][nid])
        for nid in content["shared"]["nav"]
    ]
    switchers = []
    for other in other_locales:
        href = other["dir"] if other["dir"] else "../"
        switchers.append(
            '      <a class="nav__lang" href="%s" hreflang="%s" lang="%s" aria-label="%s" title="%s">%s</a>'
            % (href, other["hreflang"], other["hreflang"], esc(t["nav"]["switchTo"]),
               esc(t["nav"]["switchTo"]), other["label"])
        )
    menu.extend(switchers)
    menu.append(
        '      <a class="nav__cta" href="%s" target="_blank" rel="noopener">\n'
        '        <svg viewBox="0 0 16 16" width="16" height="16" aria-hidden="true">'
        '<path fill="currentColor" d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 '
        '0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 '
        '1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 '
        '0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27s1.36.09 '
        '2 .27c1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 '
        '3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.01 8.01 0 0 0 16 '
        '8c0-4.42-3.58-8-8-8Z"/></svg>\n'
        '        %s\n'
        '      </a>' % (site["repoUrl"], t["nav"]["github"])
    )

    return "\n".join([
        '<header class="nav" id="nav">',
        '  <div class="wrap nav__inner">',
        '    <a class="nav__brand" href="#top">',
        '      <img src="%s%s" alt="" width="28" height="28">' % (suffix, site["logo"]),
        '      <span>%s</span>' % site["brand"],
        '    </a>',
        "",
        '    <button class="nav__toggle" id="navToggle" aria-expanded="false" aria-controls="navMenu" aria-label="%s">'
        % esc(t["nav"]["toggleLabel"]),
        '      <span></span><span></span><span></span>',
        '    </button>',
        "",
        '    <nav class="nav__menu" id="navMenu" aria-label="%s">' % esc(t["nav"]["sectionsLabel"]),
        "\n".join(menu),
        '    </nav>',
        '  </div>',
        '</header>',
    ])


def render_hero(content, shared, locale):
    t = content["i18n"][locale["code"]]
    hero = t["hero"]
    prefix = asset_prefix(locale)
    site = content["site"]
    first_shot = shared["shots"][0]

    badges = "\n".join(
        '        <li class="badge">%s</li>' % badge for badge in hero["badges"]
    )
    stats = "\n".join(
        '        <div><dt>%s</dt><dd>%s</dd></div>' % (stat["label"], stat["value"])
        for stat in hero["stats"]
    )

    return "\n".join([
        '<section class="hero" id="top">',
        '  <div class="wrap hero__inner">',
        '    <div class="hero__copy">',
        '      <h1 class="hero__title">',
        '        <img class="hero__logo" src="%s%s" alt="" width="72" height="72">' % (prefix, site["logo"]),
        '        %s' % hero["title"],
        '      </h1>',
        "",
        '      <p class="hero__tagline">%s</p>' % hero["tagline"],
        "",
        '      <p class="hero__lead">%s</p>' % hero["lead"],
        "",
        '      <ul class="badges">',
        badges,
        '      </ul>',
        "",
        '      <div class="hero__actions">',
        '        <a class="btn btn--primary" href="%s" target="_blank" rel="noopener">%s</a>'
        % (site["repoUrl"], hero["actions"]["github"]),
        '        <a class="btn" href="#build">%s</a>' % hero["actions"]["build"],
        '        <a class="btn btn--ghost" href="%s/blob/main/README.md" target="_blank" rel="noopener">%s</a>'
        % (site["repoUrl"], hero["actions"]["docs"]),
        '      </div>',
        "",
        '      <dl class="stats">',
        stats,
        '      </dl>',
        '    </div>',
        "",
        '    <figure class="hero__shot">',
        '      <div class="frame frame--tall">',
        '        <div class="frame__bar"><span class="dot"></span><span class="dot"></span>'
        '<span class="dot"></span><span class="frame__title">coeleo · desktop</span></div>',
        '        <img src="%sassets/img/shots/%s" alt="%s" width="%d" height="%d" fetchpriority="high" decoding="async">'
        % (prefix, first_shot["file"], esc(hero["heroShotAlt"]), first_shot["w"], first_shot["h"]),
        '      </div>',
        '    </figure>',
        '  </div>',
        '</section>',
    ])


def render_reuse(content, shared, locale):
    t = content["i18n"][locale["code"]]
    items = "\n".join(
        '      <li><a href="%s" target="_blank" rel="noopener">%s</a><span>%s</span></li>'
        % (item["url"], item["name"], t["reuse"]["items"][item["id"]])
        for item in shared["reuse"]
    )
    return "\n".join([
        '<section class="section section--alt" id="reuse">',
        '  <div class="wrap">',
        '    <h2 class="section__title">%s</h2>' % t["reuse"]["title"],
        '    <p class="section__lead">%s</p>' % t["reuse"]["lead"],
        "",
        '    <ul class="reuse">',
        items,
        '    </ul>',
        "",
        '    <p class="reuse__note">%s</p>' % t["reuse"]["note"],
        '  </div>',
        '</section>',
    ])


def render_features(content, shared, locale):
    t = content["i18n"][locale["code"]]
    groups = []
    for group in shared["features"]:
        group_copy = t["features"]["groups"][group["id"]]
        cards = []
        for card in group["cards"]:
            card_copy = group_copy["cards"][card]
            cards.append("\n".join([
                '        <article class="card">',
                '          <h3>%s</h3>' % card_copy["title"],
                '          <p>%s</p>' % card_copy["body"],
                '        </article>',
            ]))
        groups.append("\n".join([
            '    <div class="fgroup">',
            '      <h3 class="fgroup__title"><span>%s</span> %s</h3>' % (group["num"], group_copy["title"]),
            '      <div class="cards">',
            "\n".join(cards),
            '      </div>',
            '    </div>',
        ]))

    return "\n".join([
        '<section class="section" id="features">',
        '  <div class="wrap">',
        '    <h2 class="section__title">%s</h2>' % t["features"]["title"],
        '    <p class="section__lead">%s</p>' % t["features"]["lead"],
        "",
        "\n\n".join(groups),
        '  </div>',
        '</section>',
    ])


def render_screenshots(content, shared, locale):
    t = content["i18n"][locale["code"]]
    prefix = asset_prefix(locale)
    figures = []
    for index, shot in enumerate(shared["shots"], start=1):
        alt = t["screenshots"]["shots"][shot["id"]]
        label = "%s %d" % (t["screenshots"]["enlarge"], index)
        figures.append(
            '      <figure class="shot"><button type="button" aria-label="%s">'
            '<img src="%sassets/img/shots/%s" alt="%s" width="%d" height="%d" loading="lazy" decoding="async">'
            '</button></figure>'
            % (esc(label), prefix, shot["file"], esc(alt), shot["w"], shot["h"])
        )
    return "\n".join([
        '<section class="section section--alt" id="screenshots">',
        '  <div class="wrap">',
        '    <h2 class="section__title">%s</h2>' % t["screenshots"]["title"],
        '    <p class="section__lead">%s</p>' % t["screenshots"]["lead"],
        "",
        '    <div class="gallery" id="gallery">',
        "\n".join(figures),
        '    </div>',
        '  </div>',
        '</section>',
    ])


def render_architecture(content, shared, locale):
    t = content["i18n"][locale["code"]]
    arch = t["architecture"]
    rows = "\n".join(
        '          <tr><th scope="row">%s</th><td><code>%s</code></td><td>%s</td></tr>'
        % (arch["domains"][domain["id"]]["name"], domain["folder"], arch["domains"][domain["id"]]["role"])
        for domain in shared["domains"]
    )
    return "\n".join([
        '<section class="section" id="architecture">',
        '  <div class="wrap">',
        '    <h2 class="section__title">%s</h2>' % arch["title"],
        '    <p class="section__lead">%s</p>' % arch["lead"],
        "",
        '    <pre class="term"><code>%s</code></pre>' % render_diagram(arch["diagram"]),
        "",
        '    <div class="table-scroll">',
        '      <table>',
        '        <caption class="sr-only">%s</caption>' % esc(arch["caption"]),
        '        <thead>',
        '          <tr><th scope="col">%s</th><th scope="col">%s</th><th scope="col">%s</th></tr>'
        % (arch["headers"]["domain"], arch["headers"]["folder"], arch["headers"]["responsibility"]),
        '        </thead>',
        '        <tbody>',
        rows,
        '        </tbody>',
        '      </table>',
        '    </div>',
        '  </div>',
        '</section>',
    ])


def render_apps(content, shared, locale):
    t = content["i18n"][locale["code"]]
    apps = t["apps"]
    app_rows = "\n".join(
        '          <tr><th scope="row"><code>%s</code></th><td>%s</td></tr>'
        % (item["code"], apps["roles"][item["id"]])
        for item in shared["apps"]
    )
    lib_rows = "\n".join(
        '          <tr><th scope="row"><code>%s</code></th><td>%s</td></tr>'
        % (item["code"], apps["libRoles"][item["id"]])
        for item in shared["libs"]
    )
    return "\n".join([
        '<section class="section section--alt" id="apps">',
        '  <div class="wrap">',
        '    <h2 class="section__title">%s</h2>' % apps["title"],
        '    <p class="section__lead">%s</p>' % apps["lead"],
        "",
        '    <div class="table-scroll">',
        '      <table>',
        '        <caption class="sr-only">%s</caption>' % esc(apps["appsCaption"]),
        '        <thead><tr><th scope="col">%s</th><th scope="col">%s</th></tr></thead>'
        % (apps["appsHeaders"]["name"], apps["appsHeaders"]["role"]),
        '        <tbody>',
        app_rows,
        '        </tbody>',
        '      </table>',
        '    </div>',
        "",
        '    <div class="table-scroll">',
        '      <table>',
        '        <caption class="sr-only">%s</caption>' % esc(apps["libsCaption"]),
        '        <thead><tr><th scope="col">%s</th><th scope="col">%s</th></tr></thead>'
        % (apps["libsHeaders"]["crate"], apps["libsHeaders"]["role"]),
        '        <tbody>',
        lib_rows,
        '        </tbody>',
        '      </table>',
        '    </div>',
        '  </div>',
        '</section>',
    ])


def render_build(content, shared, locale):
    t = content["i18n"][locale["code"]]
    build = t["build"]
    spec = shared["build"]

    all_block = "# %s\nmake all\n\n# %s\nmake run" % (
        build["blockComments"]["all"],
        build["blockComments"]["run"],
    )
    other_lines = "\n".join(
        "%s  # %s" % (item["cmd"], build["otherTargetComments"][item["id"]])
        for item in spec["otherTargets"]
    )
    tests_block = "\n".join(spec["tests"])

    return "\n".join([
        '<section class="section" id="build">',
        '  <div class="wrap">',
        '    <h2 class="section__title">%s</h2>' % build["title"],
        '    <p class="section__lead">%s</p>' % build["lead"],
        "",
        '    <div class="build">',
        '      <div class="build__col">',
        '        <h3>%s</h3>' % esc(build["prereqTitle"]),
        '        <pre class="code"><code>%s</code></pre>' % esc(spec["prereq"]),
        '      </div>',
        "",
        '      <div class="build__col">',
        '        <h3>%s</h3>' % esc(build["buildTitle"]),
        '        <pre class="code"><code>%s</code></pre>' % esc(all_block),
        '      </div>',
        '    </div>',
        "",
        '    <details class="more">',
        '      <summary>%s</summary>' % esc(build["otherTargetsSummary"]),
        '      <pre class="code"><code>%s</code></pre>' % esc(other_lines),
        '    </details>',
        "",
        '    <details class="more">',
        '      <summary>%s</summary>' % esc(build["testsSummary"]),
        '      <p class="more__lead">%s</p>' % build["testsLead"],
        '      <pre class="code"><code>%s</code></pre>' % esc(tests_block),
        '    </details>',
        '  </div>',
        '</section>',
    ])


def render_roadmap(content, shared, locale):
    t = content["i18n"][locale["code"]]
    roadmap = t["roadmap"]
    bands = []
    for band in shared["roadmap"]:
        band_copy = roadmap["bands"][band["id"]]
        items = []
        for phase in band["phases"]:
            phase_copy = band_copy["phases"][phase]
            items.append("\n".join([
                '          <li>',
                '            <span class="ph">%s</span>' % phase,
                '            <div><strong>%s</strong>' % phase_copy["title"],
                '            <p>%s</p></div>' % phase_copy["body"],
                '          </li>',
            ]))
        bands.append("\n".join([
            '      <article class="band">',
            '        <header class="band__head">',
            '          <span class="pill pill--%s">%s</span>' % (band["pill"], roadmap["pills"][band["pill"]]),
            '          <h3>%s</h3>' % band_copy["title"],
            '          <p>%s</p>' % band_copy["desc"],
            '        </header>',
            '        <ul class="band__list">',
            "\n".join(items),
            '        </ul>',
            '      </article>',
        ]))

    return "\n".join([
        '<section class="section section--alt" id="roadmap">',
        '  <div class="wrap">',
        '    <h2 class="section__title">%s</h2>' % roadmap["title"],
        '    <p class="section__lead">%s</p>' % roadmap["lead"],
        "",
        '    <p class="roadmap__today">%s</p>' % roadmap["today"],
        "",
        '    <div class="roadmap">',
        "\n\n".join(bands),
        '    </div>',
        '  </div>',
        '</section>',
    ])


def render_docs(content, shared, locale):
    t = content["i18n"][locale["code"]]
    docs = t["docs"]
    items = "\n".join(
        '      <li><a href="%s" target="_blank" rel="noopener">%s</a><span>%s</span></li>'
        % (doc["url"], docs["items"][doc["id"]]["label"], docs["items"][doc["id"]]["note"])
        for doc in shared["docs"]
    )
    return "\n".join([
        '<section class="section" id="docs">',
        '  <div class="wrap">',
        '    <h2 class="section__title">%s</h2>' % docs["title"],
        "",
        '    <ul class="docs">',
        items,
        '    </ul>',
        '  </div>',
        '</section>',
    ])


def render_faq(content, locale):
    t = content["i18n"][locale["code"]]
    faq = t["faq"]
    items = []
    for entry in faq["items"]:
        items.append("\n".join([
            '      <details class="more" id="faq-%s">' % entry["id"],
            '        <summary>%s</summary>' % esc(entry["q"]),
            '        <p class="more__lead">%s</p>' % esc(entry["a"]),
            '      </details>',
        ]))
    return "\n".join([
        '<section class="section section--alt" id="faq">',
        '  <div class="wrap">',
        '    <h2 class="section__title">%s</h2>' % esc(faq["title"]),
        '    <p class="section__lead">%s</p>' % esc(faq["lead"]),
        "",
        '    <div class="faq">',
        "\n".join(items),
        '    </div>',
        '  </div>',
        '</section>',
    ])


def render_footer(content, locale):
    site = content["site"]
    t = content["i18n"][locale["code"]]
    footer = t["footer"]
    prefix = asset_prefix(locale)
    return "\n".join([
        '<footer class="footer">',
        '  <div class="wrap footer__inner">',
        '    <div class="footer__brand">',
        '      <img src="%s%s" alt="" width="24" height="24">' % (prefix, site["logo"]),
        '      <span>%s</span>' % site["brand"],
        '    </div>',
        "",
        '    <p class="footer__license">',
        '      %s' % footer["licenseHtml"],
        '    </p>',
        "",
        '    <p class="footer__note">',
        '      %s' % footer["note"],
        '    </p>',
        "",
        '    <p class="footer__links">',
        '      <a href="%s" target="_blank" rel="noopener">%s</a>' % (site["repoUrl"], esc(footer["repository"])),
        '      <a href="%s/issues" target="_blank" rel="noopener">%s</a>' % (site["repoUrl"], esc(footer["issues"])),
        '    </p>',
        '  </div>',
        '</footer>',
    ])


def render_page(content, shared, locale):
    site = content["site"]
    t = content["i18n"][locale["code"]]
    others = [candidate for candidate in site["locales"] if candidate["code"] != locale["code"]]

    body = "\n\n".join([
        render_hero(content, shared, locale),
        render_reuse(content, shared, locale),
        render_features(content, shared, locale),
        render_screenshots(content, shared, locale),
        render_architecture(content, shared, locale),
        render_apps(content, shared, locale),
        render_build(content, shared, locale),
        render_roadmap(content, shared, locale),
        render_docs(content, shared, locale),
        render_faq(content, locale),
    ])

    return "\n".join([
        render_head(content, shared, locale, others),
        "<body>",
        "",
        '<a class="skip-link" href="#main">%s</a>' % esc(t["nav"]["skip"]),
        "",
        render_nav(content, locale, others),
        "",
        '<main id="main">',
        "",
        body,
        "",
        '</main>',
        "",
        render_footer(content, locale),
        "",
        '<div class="lightbox" id="lightbox" hidden>',
        '  <button class="lightbox__close" id="lbClose" aria-label="%s">&times;</button>' % esc(t["lightbox"]["close"]),
        '  <button class="lightbox__nav lightbox__nav--prev" id="lbPrev" aria-label="%s">&#8249;</button>' % esc(t["lightbox"]["previous"]),
        '  <img id="lbImg" src="" alt="">',
        '  <button class="lightbox__nav lightbox__nav--next" id="lbNext" aria-label="%s">&#8250;</button>' % esc(t["lightbox"]["next"]),
        '</div>',
        "",
        '<script src="%sassets/js/main.js" defer></script>' % asset_prefix(locale),
        '</body>',
        '</html>',
        "",
    ])


def render_sitemap(content, shared):
    site = content["site"]
    alternates = "\n".join(
        '    <xhtml:link rel="alternate" hreflang="%s" href="%s"/>'
        % (candidate["hreflang"], page_url(site, candidate))
        for candidate in site["locales"]
    ) + '\n    <xhtml:link rel="alternate" hreflang="x-default" href="%s"/>' % page_url(
        site, site["locales"][0])

    urls = []
    for locale in site["locales"]:
        t = content["i18n"][locale["code"]]
        images = "\n".join(
            "    <image:image>\n      <image:loc>%sassets/img/shots/%s</image:loc>\n      <image:title>%s</image:title>\n    </image:image>"
            % (site["baseUrl"], shot["file"], esc(t["screenshots"]["shots"][shot["id"]]))
            for shot in shared["shots"]
        )
        urls.append("\n".join([
            "  <url>",
            "    <loc>%s</loc>" % page_url(site, locale),
            alternates,
            images,
            "  </url>",
        ]))

    return "\n".join([
        '<?xml version="1.0" encoding="UTF-8"?>',
        "<!-- %s -->" % HEADER,
        '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',
        '        xmlns:xhtml="http://www.w3.org/1999/xhtml"',
        '        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">',
        "\n".join(urls),
        "</urlset>",
        "",
    ])


def render_llms(content):
    """llms.txt: the curated index. English only - the convention is English and
    this file is consumed by machines, which link out to the localised pages."""
    site = content["site"]
    en = content["i18n"]["en"]
    llms = en["llms"]

    sections = []
    for section in llms["sections"]:
        lines = "\n".join("- %s" % line for line in section["lines"])
        sections.append("## %s\n\n%s" % (section["title"], lines))

    links = "\n".join([
        "- [Website](%s): project overview, screenshots and roadmap." % site["baseUrl"],
        "- [Portuguese (pt-BR)](%spt/): the same site in Brazilian Portuguese." % site["baseUrl"],
        "- [Source code](%s): the kernel, userspace and the design system." % site["repoUrl"],
        "- [Architecture](%s/blob/main/docs/contrib/architecture.md): technical map of the code." % site["repoUrl"],
        "- [Development guide](%s/blob/main/docs/contrib/develop.md): build, test and debug workflows." % site["repoUrl"],
        "- [Contributor index](%s/blob/main/docs/contrib/README.md): start here." % site["repoUrl"],
    ])

    return "\n".join([
        "# %s" % site["brand"],
        "",
        "> %s" % llms["summary"],
        "",
        "\n\n".join(sections),
        "",
        "## Links",
        "",
        links,
        "",
        "<!-- %s -->" % HEADER,
        "",
    ])


def render_llms_full(content, shared):
    """llms-full.txt: everything a model needs in a single fetch."""
    site = content["site"]
    en = content["i18n"]["en"]
    llms = en["llms"]

    chunks = [
        "# %s — full reference" % site["brand"],
        "",
        "> %s" % llms["summary"],
        "",
    ]

    for section in llms["sections"]:
        chunks.append("## %s" % section["title"])
        chunks.append("")
        chunks.extend("- %s" % line for line in section["lines"])
        chunks.append("")

    chunks.append("## Implemented features")
    chunks.append("")
    for group in shared["features"]:
        group_copy = en["features"]["groups"][group["id"]]
        chunks.append("### %s" % strip_tags(group_copy["title"]))
        chunks.append("")
        for card in group["cards"]:
            card_copy = group_copy["cards"][card]
            chunks.append("- %s: %s" % (strip_tags(card_copy["title"]), strip_tags(card_copy["body"])))
        chunks.append("")

    chunks.append("## Kernel domains")
    chunks.append("")
    for domain in shared["domains"]:
        copy = en["architecture"]["domains"][domain["id"]]
        chunks.append("- %s (%s): %s" % (copy["name"], domain["folder"], copy["role"]))
    chunks.append("")

    chunks.append("## Userspace applications")
    chunks.append("")
    for item in shared["apps"]:
        chunks.append("- %s: %s" % (item["code"], strip_tags(en["apps"]["roles"][item["id"]])))
    chunks.append("")

    chunks.append("## Shared libraries")
    chunks.append("")
    for item in shared["libs"]:
        chunks.append("- %s: %s" % (item["code"], strip_tags(en["apps"]["libRoles"][item["id"]])))
    chunks.append("")

    chunks.append("## Roadmap")
    chunks.append("")
    for band in shared["roadmap"]:
        band_copy = en["roadmap"]["bands"][band["id"]]
        chunks.append("### %s (%s)" % (strip_tags(band_copy["title"]), en["roadmap"]["pills"][band["pill"]]))
        chunks.append("")
        chunks.append(strip_tags(band_copy["desc"]))
        chunks.append("")
        for phase in band["phases"]:
            phase_copy = band_copy["phases"][phase]
            chunks.append("- Phase %s, %s: %s" % (phase, strip_tags(phase_copy["title"]), strip_tags(phase_copy["body"])))
        chunks.append("")

    chunks.append("## Frequently asked questions")
    chunks.append("")
    for entry in en["faq"]["items"]:
        chunks.append("### %s" % entry["q"])
        chunks.append("")
        chunks.append(entry["a"])
        chunks.append("")

    chunks.append("## Links")
    chunks.append("")
    chunks.append("- Website: %s" % site["baseUrl"])
    chunks.append("- Source: %s" % site["repoUrl"])
    chunks.append("- Architecture: %s/blob/main/docs/contrib/architecture.md" % site["repoUrl"])
    chunks.append("- Development guide: %s/blob/main/docs/contrib/develop.md" % site["repoUrl"])
    chunks.append("")
    chunks.append("<!-- %s -->" % HEADER)
    chunks.append("")

    return "\n".join(chunks)


def strip_tags(value):
    text = re.sub(r"<[^>]+>", "", value)
    return html.unescape(text).replace("\u00a0", " ").strip()


# --------------------------------------------------------------------------
# Output
# --------------------------------------------------------------------------

def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)
    print("wrote %s (%d bytes)" % (os.path.relpath(path, REPO_ROOT), len(text.encode("utf-8"))))


def relative_targets(html_text):
    """Every href/src that points inside the site (fragments and absolutes aside)."""
    targets = []
    for match in re.finditer(r'(?:href|src)="([^"#]+)"', html_text):
        target = match.group(1)
        if target.startswith(("http://", "https://", "//", "mailto:", "data:")):
            continue
        targets.append(target)
    return targets


def main():
    content = load_content()
    shared = content["shared"]
    validate(content, shared)

    outputs = {}
    for locale in content["site"]["locales"]:
        page = render_page(content, shared, locale)
        directory = os.path.join(SITE_DIR, locale["dir"]) if locale["dir"] else SITE_DIR
        outputs[os.path.join(directory, "index.html")] = page

    outputs[os.path.join(SITE_DIR, "sitemap.xml")] = render_sitemap(content, shared)
    outputs[os.path.join(SITE_DIR, "llms.txt")] = render_llms(content)
    outputs[os.path.join(SITE_DIR, "llms-full.txt")] = render_llms_full(content, shared)

    for path in sorted(outputs):
        write(path, outputs[path])

    # Sanity check after writing, so directory targets (pt/) resolve: a relative
    # link that lands on nothing is a 404 we would only catch in production.
    for path in sorted(outputs):
        if not path.endswith(".html"):
            continue
        base = os.path.dirname(path)
        for target in relative_targets(outputs[path]):
            resolved = os.path.normpath(os.path.join(base, target))
            if not os.path.exists(resolved):
                raise SystemExit("broken relative link in %s: %s"
                                 % (os.path.relpath(path, REPO_ROOT), target))
    print("relative links ok")


if __name__ == "__main__":
    main()
